version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
    container_name: e_commerce_app
    # restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev
    environment:
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      BRAND: ${BRAND}
      DB_NAME: ${DB_NAME}
