version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
    container_name: e_commerce_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev
    environment:
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
      BRAND: ${BRAND}
      MONGODB_PORT: ${MONGODB_PORT}
      DB_NAME: ${DB_NAME}
