import { Router } from "express";
import authRouter from "./Auth.route.js";
import brandRouter from "./Brand.route.js";
import catalogRouter from "./Catalog.route.js";
import categoryRouter from "./Category.route.js";
import commentRouter from "./Comment.route.js";
import couponRouter from "./Coupon.route.js";
import orderRouter from "./Order.route.js";
import productRouter from "./Product.route.js";
import rattingRouter from "./Rate.route.js";
import userRouter from "./User.route.js";
import imageRouter from "./Image.route.js";
const apiRouter = Router()
apiRouter.use("/auth", authRouter);
apiRouter.use("/brands", brandRouter);
apiRouter.use("/catalogs", catalogRouter);
apiRouter.use("/categories", categoryRouter);
apiRouter.use("/comments", commentRouter);
apiRouter.use("/coupons", couponRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/products", productRouter);
apiRouter.use("/ratings", rattingRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/images", imageRouter);
export default apiRouter;