import { Router } from "express";
import categoryController from "../controllers/Category.controller.js";
import { authJwt, authJwtAdmin } from "../middleware/authJwt.middleware.js";
import { uploadSingle } from "../middleware/multer.middleware.js";
const categoryRouter = Router();
categoryRouter.get("/", categoryController.getAllCategories);
categoryRouter.post("/", authJwtAdmin, uploadSingle, categoryController.createCategory);
categoryRouter.get("/landing", categoryController.getCategoriesForLandingPage);
categoryRouter.get("/:categoryId", categoryController.getCategoryById);
categoryRouter.delete("/:categoryId", authJwtAdmin, categoryController.deleteCategoryById);
categoryRouter.patch("/:categoryId", authJwtAdmin, uploadSingle, categoryController.updateCategoryById);
export default categoryRouter;