import { Router } from "express";
import { authJwtAdmin } from "../middleware/auth.jwt";
import productController from "../controllers/Product.controller";
const productRouter = Router();
productRouter.get("/", productController.getAllProducts);
productRouter.get("/:id", productController.getProductById);
productRouter.post("/", authJwtAdmin, productController.createProduct);
productRouter.put("/:id", authJwtAdmin, productController.updateProductById);
productRouter.delete("/:id", authJwtAdmin, productController.deleteProductById);
productRouter.post("/many", productController.createManyProducts);
export default productRouter;