import { Router } from "express";
import { authJwt, authJwtAdmin } from "../middleware/authJwt.middleware.js";
import rateController from "../controllers/Rate.controller.js";
const rateRouter = Router();
rateRouter.get("/product/:productId", rateController.getRatesByProductId);
rateRouter.post("/", authJwt, rateController.createRate);
rateRouter.delete("/:id", authJwtAdmin, rateController.deleteRateById);
rateRouter.get("/", authJwt, rateController.getAllRates);
rateRouter.get("/me/:productId", authJwt, rateController.getMyRate);
export default rateRouter;